variable "name" {
    default     = null
    type        = string
    description = "The name of the DB event subscription. By default generated by Terraform."
} 
variable "sns_topic_arn" {
    default     = null
    type        = string
    description = "The SNS topic to send events to."
}
variable "source_type" {
    default     = null
    type        = string
    description = "The type of source that will be generating the events. Valid options are db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster or db-cluster-snapshot"
}
variable "source_ids" {
    default     = null
    type        = list(string)
    description = " A list of identifiers of the event sources for which events will be returned."
}
variable "event_categories" {
    default     = null
    type        = list(string)
    description = "A list of event categories for a SourceType that you want to subscribe to."
}