#rds_subnet
variable "subnet_name" {
  description = "The name of the DB subnet group"
  type        = string
  default     = "rds-subnet-group-vpc-e99a4a82"
}


variable "subnet_description" {
  description = "The description of the DB subnet group"
  type        = string
  default     = "Created from the terraform"
}

variable "subnet_ids" {
  description = "A list of VPC subnet IDs"
  type        = list(string)
  default     = ["subnet-1418696f", "subnet-16eec15a", "subnet-a509f7ce"]
}

variable "subnet_name_prefix" {
  default = null
  type    = string

}

variable "db_subnet_tags" {
  default = null
  type    = map(string)
}

variable "db_subnet_tags_all" {
  default = null
  type    = map(string)
}


#rds_instance_dev


variable "rds_dev_db_backup_retention_period" {
  default = 0
  type  = number
  
}

variable "rds_dev_db_backup_window" {
  default = "16:35-17:05"
  type    = string
  
}

variable "rds_dev_db_ca_cert_identifier" {
  default = "rds-ca-2019"
  type    = string    
}

variable "rds_dev_db_customer_owned_ip_enabled" {
  default = false
  type    = bool
}

variable "rds_dev_db_delete_automated_backups" {
  default = true
  type    = bool
}

variable "rds_dev_db_deletion_protection" {
  default = true
  type    = bool
}

variable "rds_dev_db_iam_database_authentication_enabled" {
  default = false
  type    = bool  
}

variable "rds_dev_db_latest_restorable_time" {
  default = "0001-01-01T00:00:00Z"
  type    = string  
}

variable "rds_dev_db_license_model" {
  default = "general-public-license"
  type    = string  
}

variable "rds_dev_db_maintenance_window" {
  default = "sat:07:00-sat:07:30"
  type    = string
}

variable "rds_dev_db_replicas" {
  default = null
  type    = list(string)
}

variable "rds_dev_db_instance_name" {
  default     = "prj1_dev"
  type        = string
  description = "The db name to create. If omitted, no database is created initially"
}

variable "rds_dev_db_option_group_id" {
  default = "rds-dev-core-001-option-group"
  type    = string 
}

variable "rds_dev_db_parameter_group_id" {
  default = "rds-dev-core-001-parameter-group"
  type    = string 
}

variable "rds_dev_db_identifier" {
  default     = "rds-dev-core-001-development-db"
  type        = string
  description = "Name in which db is created"
}

variable "rds_dev_db_auto_minor_version_upgrade" {
  default = true
  type    = bool
  
}

variable "rds_dev_db_port" {
  default     = 3306
  type        = number
  description = "The port on which the db accepts connections"
}

variable "rds_dev_db_engine" {
  default     = "mysql"
  type        = string
  description = "Engine type necessary for the database"
}

variable "rds_dev_db_engine_version" {
  default     = "8.0.28" 
  type        = string
  description = "The engine versions that support the database features"
}


variable "rds_dev_db_instance_class" {
  default     = "db.t3.micro"
  type        = string
  description = "The instance type of the RDS instance"
}

variable "rds_dev_db_allocated_storage" {
  default     = 20
  type        = number
  description = "The allocated storage in gigabytes"
}

variable "rds_dev_db_max_allocated_storage" {
  default     = 1000
  type        = number
  description = "The maximum allocated storage in gigabytes"
}

variable "rds_dev_db_monitoring_interval" {
  default = 0
  type    = number
}

variable "rds_dev_db_skip_final_snapshot" {
  default = true
  type    = bool
}

variable "rds_dev_db_security_group_id" {
  default     = ["sg-858500fb"]
  type        = list(string)
  description = "List of VPC security groups to associate"
}

# notification
variable "rds_instance_dev_event_notification_name" {
    default     = "rds-dev-core-001-event-subscription"
    type        = string
    description = "The name of the DB event subscription. By default generated by Terraform."
} 
variable "rds_instance_dev_event_notification_source_type" {
    default     = "db-instance"
    type        = string
    description = "The type of source that will be generating the events. Valid options are db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster or db-cluster-snapshot"
}
variable "rds_instance_dev_event_notification_source_ids" {
    default     = null
    type        = list(string)
    description = " A list of identifiers of the event sources for which events will be returned."
}
variable "rds_instance_dev_event_notification_event_categories" {
    default     = ["configuration change", "creation", "deletion","availability", "failure","security"]
    type        = list(string)
    description = "A list of event categories for a SourceType that you want to subscribe to."
}

variable "rds_dev_db_multi_az" {
  default     = false
  description = "The buildment options for mysql"
  type        = bool
}


variable "rds_dev_db_allow_major_version_upgrade" {
  default = false
  type    = bool
}

variable "rds_dev_db_apply_immediately" {
  default = true
  type    = bool
}

variable "rds_dev_db_availability_zone" {
  default = "ap-south-1a"
  type    = string
}

variable "rds_dev_db_character_set_name" {
  default = null
  type    = string
}

variable "rds_dev_db_copy_tags_to_snapshot" {
  default = true
  type    = bool

}

variable "rds_dev_db_domain" {
  default = null
  type    = string

}

variable "rds_dev_db_domain_iam_role_name" {
  default = null
  type    = string
}

variable "rds_dev_db_enabled_cloudwatch_logs_exports" {
  default = ["audit", "error", "general", "slowquery"]
  type    = list(string)
}


variable "rds_dev_db_final_snapshot_identifier" {
  default = null
  type    = string
}

variable "rds_dev_db_identifier_prefix" {
  default = null
  type    = string
}

variable "rds_dev_db_iops" {
  default = 0
  type    = number
}

variable "rds_dev_db_kms_key_id" {
  default = null
  type    = string
}

variable "rds_dev_db_monitoring_role_arn" {
  default = null
  type    = string
}

variable "rds_dev_db_nchar_character_set_name" {
  default = null
  type    = string
}

variable "rds_dev_db_performance_insights_enabled" {
  default = false
  type    = bool
}
variable "rds_dev_db_performance_insights_kms_key_id" {
  default = "arn:aws:kms:ap-south-1:334455221100:key/730c4e5a-4e7f-44db-97b8-0f7f0e53e4fc"
  type    = string
}

variable "rds_dev_db_performance_insights_retention_period" {
  default = 0
  type    = number
}

variable "rds_dev_db_publicly_accessible" {
  default = true
  type    = bool
}

variable "rds_dev_db_replicate_source_db" {
  default = null
  type    = string
}

variable "rds_dev_db_snapshot_identifier" {
  default = null
  type    = string
}

variable "rds_dev_db_storage_encrypted" {
  default = false
  type    = bool
}

variable "rds_dev_db_timezone" {
  default = null
  type    = string
}

variable "rds_dev_db_storage_type" {
  default = "gp2"
  type    = string
}

variable "rds_dev_db_tags" {
  default = {
    dev = "autoshutdown"
  }
  type    = map(string)
}

variable "rds_dev_db_tags_all" {
  default = {
    dev = "autoshutdown"
  }
  type    = map(string)
}

#rds_instance_test


variable "rds_test_db_backup_retention_period" {
  default = 7
  type  = number
}

variable "rds_test_db_backup_window" {
  default = "23:26-23:56"
  type    = string 
}

variable "rds_test_db_ca_cert_identifier" {
  default = "rds-ca-2019"
  type    = string    
}

variable "rds_test_db_customer_owned_ip_enabled" {
  default = false
  type    = bool
}

variable "rds_test_db_delete_automated_backups" {
  default = false
  type    = bool
}

variable "rds_test_db_deletion_protection" {
  default = true
  type    = bool
}

variable "rds_test_db_iam_database_authentication_enabled" {
  default = false
  type    = bool  
}

variable "rds_test_db_lards_test_db_restorable_time" {
  default = "2022-05-18T11:00:00Z"
  type    = string  
}

variable "rds_test_db_license_model" {
  default = "general-public-license"
  type    = string  
}

variable "rds_test_db_maintenance_window" {
  default = "sun:09:56-sun:10:26"
  type    = string
}

variable "rds_test_db_monitoring_interval" {
  default = 0
  type    = number
}

variable "rds_test_db_replicas" {
  default = null
  type    = list(string)
}

variable "rds_test_db_instance_name" {
  default     = "prj1_test"
  type        = string
  description = "The db name to create. If omitted, no database is created initially"
}

variable "rds_test_db_option_group_id" {
  default = "default:mysql-8-0"
  type    = string 
}

variable "rds_test_db_parameter_group_id" {
  default = "rds-dev-core-001-parameter-group"
  type    = string 
}

variable "rds_test_db_identifier" {
  default     = "rds-dev-core-001-test-db"
  type        = string
  description = "Name in which db is created"
}

variable "rds_test_db_auto_minor_version_upgrade" {
  default = false
  type    = bool
  
}

variable "rds_test_db_port" {
  default     = 3306
  type        = number
  description = "The port on which the db accepts connections"
}

variable "rds_test_db_engine" {
  default     = "mysql"
  type        = string
  description = "Engine type necessary for the database"
}

variable "rds_test_db_engine_version" {
  default     = "8.0.23"
  description = "The engine versions that support the database features"
}


variable "rds_test_db_instance_class" {
  default     = "db.t3.micro"
  type        = string
  description = "The instance type of the RDS instance"
}

variable "rds_test_db_allocated_storage" {
  default     = 20
  type        = number
  description = "The allocated storage in gigabytes"
}

variable "rds_test_db_max_allocated_storage" {
  default     = 1000
  type        = number
  description = "The maximum allocated storage in gigabytes"
}

variable "rds_test_db_skip_final_snapshot" {
  default = true
  type    = bool
}

variable "rds_test_db_security_group_id" {
  default     = ["sg-858500fb"]
  type        = list(string)
  description = "List of VPC security groups to associate"
}

variable "rds_test_db_multi_az" {
  default     = false
  description = "The buildment options for mysql"
  type        = bool
}


variable "rds_test_db_allow_major_version_upgrade" {
  default = false
  type    = bool
}

variable "rds_test_db_apply_immediately" {
  default = true
  type    = bool
}

variable "rds_test_db_availability_zone" {
  default = "ap-south-1c"
  type    = string
}

variable "rds_test_db_character_set_name" {
  default = null
  type    = string
}

variable "rds_test_db_copy_tags_to_snapshot" {
  default = true
  type    = bool

}

variable "rds_test_db_domain" {
  default = null
  type    = string

}

variable "rds_test_db_domain_iam_role_name" {
  default = null
  type    = string
}

variable "rds_test_db_enabled_cloudwatch_logs_exports" {
  default = ["audit","error","general","slowquery"]
  type    = list(string)
}


variable "rds_test_db_final_snapshot_identifier" {
  default = null
  type    = string
}

variable "rds_test_db_identifier_prefix" {
  default = null
  type    = string
}

variable "rds_test_db_iops" {
  default = 0
  type    = number
}

variable "rds_test_db_kms_key_id" {
  default = "arn:aws:kms:ap-south-1:334455221100:key/730c4e5a-4e7f-44db-97b8-0f7f0e53e4fc"
  type    = string
}

variable "rds_test_db_monitoring_role_arn" {
  default = null
  type    = string
}

variable "rds_test_db_nchar_character_set_name" {
  default = null
  type    = string
}

variable "rds_test_db_performance_insights_enabled" {
  default = false
  type    = bool
}
variable "rds_test_db_performance_insights_kms_key_id" {
  default = null
  type    = string
}

variable "rds_test_db_performance_insights_retention_period" {
  default = 0
  type    = number
}

variable "rds_test_db_publicly_accessible" {
  default = true
  type    = bool
}

variable "rds_test_db_replicate_source_db" {
  default = null
  type    = string
}

variable "rds_test_db_snapshot_identifier" {
  default = null
  type    = string
}

variable "rds_test_db_storage_encrypted" {
  default = true
  type    = bool
}

variable "rds_test_db_timezone" {
  default = null
  type    = string
}

variable "rds_test_db_storage_type" {
  default = "gp2"
  type    = string
}

variable "rds_test_db_tags" {
  default = {
    test = "autoshutdown"
  }
  type    = map(string)
}

variable "rds_test_db_tags_all" {
  default = {
    test = "autoshutdown"
  }
  type    = map(string)
}
variable "rds_dev_db_username" {
  default     = "prj1_admin"
  type        = string

}
variable "rds_test_db_username" {
  default     = "prj1_admin"
  type        = string

}



variable "rds_demo_db_backup_retention_period" {
  default = 7
  type  = number
  
}

variable "rds_demo_db_backup_window" {
  default = "16:35-17:05"
  type    = string
  
}

variable "rds_demo_db_ca_cert_identifier" {
  default = "rds-ca-2019"
  type    = string    
}

variable "rds_demo_db_customer_owned_ip_enabled" {
  default = false
  type    = bool
}

variable "rds_demo_db_delete_automated_backups" {
  default = false
  type    = bool
}

variable "rds_demo_db_deletion_protection" {
  default = true
  type    = bool
}

variable "rds_demo_db_iam_database_authentication_enabled" {
  default = false
  type    = bool  
}

variable "rds_demo_db_latest_restorable_time" {
  default = "0001-01-01T00:00:00Z"
  type    = string  
}

variable "rds_demo_db_license_model" {
  default = "general-public-license"
  type    = string  
}

variable "rds_demo_db_maintenance_window" {
  default = "thu:06:55-thu:07:25"
  type    = string
}

variable "rds_demo_db_replicas" {
  default = null
  type    = list(string)
}

variable "rds_demo_db_instance_name" {
  default     = "prj1_demo"
  type        = string
  description = "The db name to create. If omitted, no database is created initially"
}

variable "rds_demo_db_option_group_id" {
  default = "rds-dev-core-001-option-group"
  type    = string 
}

variable "rds_demo_db_parameter_group_id" {
  default = "rds-dev-core-001-parameter-group"
  type    = string 
}

variable "rds_demo_db_identifier" {
  default     = "rds-demo-core-001-demo-db"
  type        = string
  description = "Name in which db is created"
}

variable "rds_demo_db_auto_minor_version_upgrade" {
  default = true
  type    = bool
  
}
variable "rds_demo_db_username" {
  default     = "prj1_admin"
  type        = string
  #description = "Name in which db is created"
}

variable "rds_demo_db_port" {
  default     = 4412
  type        = number
  description = "The port on which the db accepts connections"
}

variable "rds_demo_db_engine" {
  default     = "mysql"
  type        = string
  description = "Engine type necessary for the database"
}

variable "rds_demo_db_engine_version" {
  default     = "8.0.28"
  type        = string
  description = "The engine versions that support the database features"
}


variable "rds_demo_db_instance_class" {
  default     = "db.t3.micro"
  type        = string
  description = "The instance type of the RDS instance"
}

variable "rds_demo_db_allocated_storage" {
  default     = 20
  type        = number
  description = "The allocated storage in gigabytes"
}

variable "rds_demo_db_max_allocated_storage" {
  default     = 1000
  type        = number
  description = "The maximum allocated storage in gigabytes"
}

variable "rds_demo_db_skip_final_snapshot" {
  default = false
  type    = bool
}

variable "rds_demo_db_security_group_id" {
  default     = ["sg-858500fb"]
  type        = list(string)
  description = "List of VPC security groups to associate"
}

variable "rds_demo_db_multi_az" {
  default     = false
  description = "The buildment options for mysql"
  type        = bool
}


variable "rds_demo_db_allow_major_version_upgrade" {
  default = false
  type    = bool
}

variable "rds_demo_db_apply_immediately" {
  default = true
  type    = bool
}

variable "rds_demo_db_availability_zone" {
  default = "ap-south-1a"
  type    = string
}

variable "rds_demo_db_character_set_name" {
  default = null
  type    = string
}

variable "rds_demo_db_copy_tags_to_snapshot" {
  default = true
  type    = bool

}

variable "rds_demo_db_domain" {
  default = null
  type    = string

}

variable "rds_demo_db_domain_iam_role_name" {
  default = null
  type    = string
}

variable "rds_demo_db_enabled_cloudwatch_logs_exports" {
  default = ["audit", "error", "general", "slowquery"]
  type    = list(string)
}


variable "rds_demo_db_final_snapshot_identifier" {
  default = "rds-demo-core-001-demo-db-snapshot-3"
  type    = string
}

variable "rds_demo_db_identifier_prefix" {
  default = null
  type    = string
}

variable "rds_demo_db_iops" {
  default = 0
  type    = number
}

variable "rds_demo_db_kms_key_id" {
  default = null
  type    = string
}

variable "rds_demo_db_nchar_character_set_name" {
  default = null
  type    = string
}

variable "rds_demo_db_performance_insights_enabled" {
  default = false
  type    = bool
}
variable "rds_demo_db_performance_insights_kms_key_id" {
  default = null
  type    = string
}

variable "rds_demo_db_performance_insights_retention_period" {
  default = 0
  type    = number
}

variable "rds_demo_db_publicly_accessible" {
  default = true
  type    = bool
}

variable "rds_demo_db_replicate_source_db" {
  default = null
  type    = string
}

variable "rds_demo_db_snapshot_identifier" {
  default = null
  type    = string
}

variable "rds_demo_db_storage_encrypted" {
  default = true
  type    = bool
}

variable "rds_demo_db_timezone" {
  default = null
  type    = string
}

variable "rds_demo_db_storage_type" {
  default = "gp2"
  type    = string
}

variable "rds_demo_db_tags" {
  default = {
    demo = "autoshutdown"
  }
  type    = map(string)
}

variable "rds_demo_db_tags_all" {
  default = {
    demo = "autoshutdown"
  }
  type    = map(string)
}

variable "rds_demo_db_monitoring_interval" {
  default = 60
  type    = number
}

variable "rds_demo_db_monitoring_role_arn" {
  default = null
  type    = string
}
variable "db_snapshot_identifier" {
  default = "rds-dev-core-001-demo-db"
  type    = string
}